export const LOAD_USERS_START = "LOAD_USERS_START"
export const LOAD_ADDRESS_START = "LOAD_ADDRESS_START"
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS"
export const LOAD_USERS_ERROR = "LOAD_USERS_ERROR"

export const CREATE_USER_START = "CREATE_USER_START"
export const CREATE_ADDRESS_START = "CREATE_ADDRESS_START"
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS"
export const CREATE_USER_ERROR = "CREATE_USER_ERROR"

export const DELETE_USER_START = "DELETE_USER_START"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_ERROR = "DELETE_USER_ERROR"

export const UPDATE_USER_START = "UPDATE_USER_START"
export const UPDATE_ADDRESS_START = "UPDATE_ADDRESS_START"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR"

export const SUBMIT_BASIC_INFO = "SUBMIT_BASIC_INFO"
export const SUBMIT_ADDRESS_INFO = "SUBMIT_ADDRESS_INFO"
export const SUBMIT_COMBINED_FORM = "SUBMIT_COMBINED_FORM"
